version: "3"

services:
  mc:
    image: ${IMAGE:-itzg/minecraft-server}
    ports:
      - 0.0.0.0:25565:25565      # Java server
      - 0.0.0.0:24454:24454/udp  # Voice
      - 0.0.0.0:19132:19132/udp  # Bedrock server
      - 127.0.0.1:63830:63830    # Dynmap
    environment:
      EULA: "true"
      TYPE: FABRIC
      MEMORY: 2G
      TZ: Asis/Shanghai
    restart: unless-stopped
    volumes:
      - fabric:/data

volumes:
  fabric:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/srv/fabric'
