version: "3"

services:
  mc:
    image: ${IMAGE:-itzg/minecraft-server}
    ports:
      - 25565:25565
    environment:
      EULA: "true"
      TYPE: FABRIC
      MEMORY: 2G
      TZ: Asis/Shanghai
    restart: unless-stopped
    volumes:
      - fabric:/data

volumes:
  fabric:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/srv/fabric'
